apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pfbfi6n96-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pfbfi6n96-python 
  name: pfbfi6n96-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pfbfi6n96-python 
