apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pfbfi6n96-python 
  janus-idp.io/tekton: pfbfi6n96-python
  backstage.io/kubernetes-id: pfbfi6n96-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pfbfi6n96-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  